import Foundation
import CryptoKit
import CommonCrypto
import P256K

/// BIP39 and BIP32 — the derivation the daemon uses, ported so that the same
/// seed produces the same keys on both.
///
/// The contract this mirrors, exactly:
///
/// ```ts
/// const seed = new Mnemonic(phrase).toSeed();      // BIP39, PBKDF2-HMAC-SHA512
/// const hd = HD.fromSeed(seed);                    // BIP32 master
/// const child = hd.derive("m/0/0");                // the daemon's spend path
/// child.privKey.toPublicKey().toAddress();         // P2PKH
/// ```
///
/// `packages/walletd/test/vectors/wallet-vectors.json` holds the expected
/// outputs for three phrases, generated by that same library. The tests here
/// reproduce them byte for byte, which is what makes "same seed on both" true
/// rather than hoped for.
public enum BIP39 {
    public enum Error: Swift.Error, Equatable {
        case emptyPhrase
        case wrongWordCount(Int)
        case unknownWord(String)
        case badChecksum
    }

    /// PBKDF2-HMAC-SHA512, 2048 iterations, salt "mnemonic" — the BIP39 seed.
    ///
    /// Note what is *not* validated here: nothing. Callers should use
    /// `seed(fromValidated:)` when the phrase came from a person, because a
    /// single mistyped word otherwise derives a valid-looking but different
    /// wallet, and the user would be told their phrase was wrong by an empty
    /// balance much later.
    public static func seed(from phrase: String, passphrase: String = "") -> [UInt8] {
        let normalized = normalize(phrase)
        let salt = Array(("mnemonic" + passphrase).utf8)
        var derived = [UInt8](repeating: 0, count: 64)
        let password = Array(normalized.utf8)
        let status = salt.withUnsafeBufferPointer { saltBuffer in
            password.withUnsafeBufferPointer { passwordBuffer in
                CCKeyDerivationPBKDF(
                    CCPBKDFAlgorithm(kCCPBKDF2),
                    passwordBuffer.baseAddress?.withMemoryRebound(to: CChar.self, capacity: password.count) { $0 },
                    password.count,
                    saltBuffer.baseAddress?.withMemoryRebound(to: UInt8.self, capacity: salt.count) { $0 },
                    salt.count,
                    CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA512),
                    2048,
                    &derived,
                    derived.count
                )
            }
        }
        // PBKDF2 with these parameters cannot fail for valid inputs; a non-zero
        // status would mean a programming error, and returning a short seed
        // would be worse than stopping.
        precondition(status == kCCSuccess, "PBKDF2 failed with status \(status)")
        return derived
    }

    /// Validate the phrase (word list + checksum), then derive.
    public static func seed(fromValidated phrase: String) throws -> [UInt8] {
        try validate(phrase)
        return seed(from: phrase)
    }

    public static func normalize(_ phrase: String) -> String {
        phrase
            .lowercased()
            .components(separatedBy: CharacterSet.letters.inverted)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
    }

    /// Full BIP39 validation: known words, and the SHA-256 checksum the last
    /// word carries.
    public static func validate(_ phrase: String) throws {
        let words = normalize(phrase).split(separator: " ").map(String.init)
        guard !words.isEmpty else { throw Error.emptyPhrase }
        guard [12, 15, 18, 21, 24].contains(words.count) else { throw Error.wrongWordCount(words.count) }

        let list = try wordlist()
        var indices = [Int]()
        indices.reserveCapacity(words.count)
        for word in words {
            guard let index = list[word] else { throw Error.unknownWord(word) }
            indices.append(index)
        }

        // 11 bits per word: entropy is the leading bits, the remainder is the
        // checksum of that entropy's SHA-256.
        var bits = [Bool]()
        bits.reserveCapacity(words.count * 11)
        for index in indices {
            for shift in stride(from: 10, through: 0, by: -1) {
                bits.append((index >> shift) & 1 == 1)
            }
        }
        let checksumBits = words.count * 11 / 33
        let entropyBits = bits.count - checksumBits
        var entropy = [UInt8]()
        entropy.reserveCapacity(entropyBits / 8)
        for byteStart in stride(from: 0, to: entropyBits, by: 8) {
            var byte: UInt8 = 0
            for offset in 0..<8 where byteStart + offset < entropyBits {
                byte = byte << 1 | (bits[byteStart + offset] ? 1 : 0)
            }
            entropy.append(byte)
        }

        let digest = Array(SHA256.hash(data: Data(entropy)))
        for index in 0..<checksumBits {
            let expected = (digest[index / 8] >> (7 - UInt8(index % 8))) & 1 == 1
            guard bits[entropyBits + index] == expected else { throw Error.badChecksum }
        }
    }

    /// The English word list, loaded from the package resource.
    ///
    /// A dictionary for lookups; the order is what carries the index, and the
    /// tests assert the two ends of it rather than trusting the file.
    public static func wordlist() throws -> [String: Int] {
        if let cached = cachedWordlist { return cached }
        guard let url = Bundle.module.url(forResource: "bip39-english", withExtension: "txt"),
              let text = try? String(contentsOf: url, encoding: .utf8)
        else {
            throw WordlistError.missing
        }
        let words = text.split(separator: "\n").map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        var map = [String: Int]()
        map.reserveCapacity(words.count)
        for (index, word) in words.enumerated() { map[word] = index }
        cachedWordlist = map
        return map
    }

    public enum WordlistError: Swift.Error { case missing }
    private nonisolated(unsafe) static var cachedWordlist: [String: Int]?
}

/// BIP32.
public enum BIP32 {
    public enum Error: Swift.Error, Equatable {
        case badPath(String)
        case invalidKey
        case derivationFailed(String)
    }

    public struct ExtendedKey {
        public let privateKey: [UInt8]
        public let chainCode: [UInt8]
        public var publicKey: [UInt8] { try! Secp256k1.publicKey(fromPrivateKey: privateKey) }

        public init(privateKey: [UInt8], chainCode: [UInt8]) {
            self.privateKey = privateKey
            self.chainCode = chainCode
        }
    }

    /// BIP32 master key: `I = HMAC-SHA512("Bitcoin seed", seed)`.
    public static func master(fromSeed seed: [UInt8]) throws -> ExtendedKey {
        let hmac = HMAC<SHA512>.authenticationCode(for: Data(seed), using: SymmetricKey(data: Data("Bitcoin seed".utf8)))
        let bytes = Array(hmac)
        let key = Array(bytes.prefix(32))
        let chain = Array(bytes.suffix(32))
        try Secp256k1.validatePrivateKey(key)
        return ExtendedKey(privateKey: key, chainCode: chain)
    }

    /// Derive a path like `m/0/0` or `m/44'/0'/0'/0/0`.
    ///
    /// Hardened indices (`'` or `h`) are the ones BIP44 uses; the daemon's own
    /// spend path is plain `m/0/0`, and both are exercised by the vectors.
    public static func derive(_ path: String, from parent: ExtendedKey) throws -> ExtendedKey {
        let components = path.split(separator: "/").map(String.init)
        guard let first = components.first, first == "m" || first == "M" else {
            throw Error.badPath(path)
        }
        var key = parent
        for component in components.dropFirst() {
            let hardened = component.hasSuffix("'") || component.hasSuffix("h") || component.hasSuffix("H")
            let digits = hardened ? String(component.dropLast()) : component
            guard let index = UInt32(digits), index < 0x8000_0000 else { throw Error.badPath(path) }
            let childIndex = hardened ? index + 0x8000_0000 : index
            key = try child(of: key, index: childIndex)
        }
        return key
    }

    /// One child step. Non-hardened uses the parent *public* key, which is why
    /// the compressed serialization matters here.
    static func child(of parent: ExtendedKey, index: UInt32) throws -> ExtendedKey {
        var data = Data()
        if index >= 0x8000_0000 {
            data.append(0x00)
            data.append(contentsOf: parent.privateKey)
        } else {
            data.append(contentsOf: try Secp256k1.publicKey(fromPrivateKey: parent.privateKey))
        }
        data.append(UInt8((index >> 24) & 0xff))
        data.append(UInt8((index >> 16) & 0xff))
        data.append(UInt8((index >> 8) & 0xff))
        data.append(UInt8(index & 0xff))

        let hmac = HMAC<SHA512>.authenticationCode(for: data, using: SymmetricKey(data: Data(parent.chainCode)))
        let bytes = Array(hmac)
        let left = Array(bytes.prefix(32))
        let chain = Array(bytes.suffix(32))

        // child = (IL + k) mod n. Both operands are below the curve order, so
        // the sum is below 2n and a single conditional subtraction is the whole
        // of the modular reduction — no general-purpose big-number arithmetic
        // needed for the one operation BIP32 requires.
        let childKey = try ScalarArithmetic.addModN(left, parent.privateKey)
        try Secp256k1.validatePrivateKey(childKey)
        return ExtendedKey(privateKey: childKey, chainCode: chain)
    }
}

/// 256-bit addition modulo the secp256k1 order, on 64-bit limbs.
///
/// Deliberately small and dull: the vectors decide whether it is right, and the
/// one place it could go wrong (carry propagation) is exercised by every
/// non-hardened derivation in the test set.
enum ScalarArithmetic {
    /// n = FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE BAAEDCE6 AF48A03B BFD25E8C D0364141
    static let order: [UInt64] = [
        0xBFD2_5E8C_D036_4141,
        0xBAAE_DCE6_AF48_A03B,
        0xFFFF_FFFF_FFFF_FFFE,
        0xFFFF_FFFF_FFFF_FFFF,
    ]

    static func addModN(_ a: [UInt8], _ b: [UInt8]) throws -> [UInt8] {
        guard a.count == 32, b.count == 32 else { throw BIP32.Error.invalidKey }
        var sum = [UInt64](repeating: 0, count: 4)
        var carry = false
        for limb in 0..<4 {
            let aLimb = limbs(a)[limb]
            let bLimb = limbs(b)[limb]
            let (partial, overflow1) = aLimb.addingReportingOverflow(bLimb)
            let (total, overflow2) = partial.addingReportingOverflow(carry ? 1 : 0)
            sum[limb] = total
            carry = overflow1 || overflow2
        }

        // One conditional subtraction, valid because a + b < 2n.
        //
        // The default matters: a sum exactly equal to n must reduce to zero, so
        // "equal so far" has to mean "reduce". Getting that backwards returns n
        // instead of 0 — a bug no derivation vector would ever hit (the odds are
        // about 2^-256) and only a boundary test can find.
        var needsReduce = true
        if !carry {
            for limb in stride(from: 3, through: 0, by: -1) {
                if sum[limb] < order[limb] { needsReduce = false; break }
                if sum[limb] > order[limb] { needsReduce = true; break }
            }
        }
        if needsReduce {
            var borrow = false
            for limb in 0..<4 {
                let (partial, underflow1) = sum[limb].subtractingReportingOverflow(order[limb])
                let (total, underflow2) = partial.subtractingReportingOverflow(borrow ? 1 : 0)
                sum[limb] = total
                borrow = underflow1 || underflow2
            }
        }
        return bytes(sum)
    }

    /// Little-endian limbs from a big-endian 32-byte key.
    static func limbs(_ key: [UInt8]) -> [UInt64] {
        var out = [UInt64](repeating: 0, count: 4)
        for limb in 0..<4 {
            var value: UInt64 = 0
            for offset in 0..<8 {
                value = value << 8 | UInt64(key[(3 - limb) * 8 + offset])
            }
            out[limb] = value
        }
        return out
    }

    static func bytes(_ limbs: [UInt64]) -> [UInt8] {
        var out = [UInt8]()
        out.reserveCapacity(32)
        for limb in stride(from: 3, through: 0, by: -1) {
            for shift in stride(from: 56, through: 0, by: -8) {
                out.append(UInt8((limbs[limb] >> UInt64(shift)) & 0xff))
            }
        }
        return out
    }
}
