// swift-tools-version: 6.0
import PackageDescription

// The bsvOS iOS client. See ../../docs/ios.md for the design and threat model.
//
// Scope note: this package contains the *client* half of bsvOS on iOS — the
// BRC-100 call surface, the wire types, and the Phase 0 device transport. It
// deliberately contains no cryptography: custody stays in the daemon for now,
// and a test asserts the device surface cannot reach key-material methods.
let package = Package(
    name: "BSVOSWallet",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "BSVOSWallet", targets: ["BSVOSWallet"]),
    ],
    dependencies: [
        // secp256k1 for iOS. CryptoKit has no secp256k1, so this is the one
        // dependency the standalone wallet cannot avoid — and it is the only
        // place a signing bug could come from, which is why the port is
        // verified against vectors generated by the daemon rather than against
        // its own expectations.
        .package(url: "https://github.com/21-DOT-DEV/swift-secp256k1", from: "0.21.0"),
    ],
    targets: [
        .target(
            name: "BSVOSWallet",
            dependencies: [
                .product(name: "P256K", package: "swift-secp256k1"),
            ],
            resources: [
                // The BIP39 English word list. Needed to *validate* a phrase as
                // well as generate one: a single mistyped word otherwise derives
                // a different wallet, and the user would learn that from an
                // empty balance much later.
                .copy("Resources/bip39-english.txt"),
            ]
        ),
        .testTarget(name: "BSVOSWalletTests", dependencies: ["BSVOSWallet"]),
    ]
)
