import XCTest
@testable import BSVOSWallet

/// The port's acceptance test: the Swift must derive exactly what the daemon
/// derives, from the same seed.
///
/// The vectors are generated by the daemon's own library
/// (`packages/walletd/test/vectors/generate.mjs`, which calls `@bsv/sdk` the way
/// `custody.ts` does). That makes the TypeScript the reference implementation
/// for this port, which is the only honest way to claim "same seed on both" —
/// asserting against values the Swift itself produced would prove only that it
/// agrees with itself.
///
/// One vector is an independent check on top of that: `m/44'/0'/0'/0/0` for the
/// BIP39 specification's test phrase yields `1LqBGSKuX5yYUonjxT5qGfpUsXKYYWeabA`,
/// the published BIP44 test vector. If the whole chain — PBKDF2, HMAC-SHA512,
/// scalar arithmetic, secp256k1, RIPEMD160, Base58Check — had drifted together,
/// that address would not match.
final class WalletVectorTests: XCTestCase {
    private struct Vectors: Decodable {
        struct Path: Decodable {
            let privateKeyHex: String
            let publicKeyHex: String
            let address: String
            let wif: String
        }
        struct Signing: Decodable {
            let digestHex: String
            let signatureHex: String?
        }
        let phrase: String
        let seedHex: String
        let paths: [String: Path]
        let signingVector: Signing?
    }

    private func loadVectors() throws -> [Vectors] {
        // The daemon's vectors, read from the repo rather than copied, so the
        // two cannot drift apart in a file nobody regenerates.
        let here = URL(fileURLWithPath: #filePath)
        let repoRoot = here
            .deletingLastPathComponent()   // BSVOSWalletTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // ios
            .deletingLastPathComponent()   // packages
        let url = repoRoot.appendingPathComponent("walletd/test/vectors/wallet-vectors.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode([Vectors].self, from: data)
    }

    func testTheVectorsArePresentAndLookRight() throws {
        let vectors = try loadVectors()
        XCTAssertEqual(vectors.count, 3, "three phrases")
        // A canary on the file itself: if the generator silently produced
        // nothing, every test below would pass vacuously.
        let paths = try XCTUnwrap(vectors.first?.paths)
        XCTAssertEqual(paths["m/0/0"]?.address.count, 34, "a mainnet P2PKH address")
        XCTAssertTrue(paths["m/0/0"]?.address.hasPrefix("1") ?? false, "mainnet addresses start with 1")
    }

    func testSeedMatchesBIP39() throws {
        for vector in try loadVectors() {
            let seed = BIP39.seed(from: vector.phrase)
            XCTAssertEqual(Hex.encode(seed), vector.seedHex, "seed for: \(vector.phrase.prefix(24))…")
        }
    }

    func testDerivationMatchesTheDaemonForEveryPath() throws {
        for vector in try loadVectors() {
            let master = try BIP32.master(fromSeed: BIP39.seed(from: vector.phrase))
            for (path, expected) in vector.paths {
                let child = try BIP32.derive(path, from: master)
                XCTAssertEqual(Hex.encode(child.privateKey), expected.privateKeyHex, "private key at \(path)")

                let publicKey = try Secp256k1.publicKey(fromPrivateKey: child.privateKey)
                XCTAssertEqual(Hex.encode(publicKey), expected.publicKeyHex, "public key at \(path)")
                XCTAssertEqual(publicKey.count, 33, "compressed, as the daemon serializes it")

                XCTAssertEqual(Address.from(publicKey: publicKey), expected.address, "address at \(path)")
            }
        }
    }

    /// The daemon's own spend path, named explicitly. Everything else about the
    /// wallet hangs off this one derivation.
    func testTheSpendPathAddressIsIdentical() throws {
        for vector in try loadVectors() {
            let master = try BIP32.master(fromSeed: BIP39.seed(from: vector.phrase))
            let spend = try BIP32.derive("m/0/0", from: master)
            let expected = try XCTUnwrap(vector.paths["m/0/0"])
            XCTAssertEqual(Address.from(publicKey: try Secp256k1.publicKey(fromPrivateKey: spend.privateKey)),
                           expected.address)
        }
    }

    func testSignatureIsProducedAndVerifies() throws {
        let vectors = try loadVectors()
        let signing = try XCTUnwrap(vectors.first?.signingVector, "a signing vector")
        let master = try BIP32.master(fromSeed: BIP39.seed(from: vectors[0].phrase))
        let key = try BIP32.derive("m/0/0", from: master)

        let digest = try Hex.decode(signing.digestHex)
        let signature = try Secp256k1.sign(derForDigest: digest, withPrivateKey: key.privateKey)
        XCTAssertGreaterThan(signature.count, 60, "a DER signature")

        // Verified against the public key: a signature that cannot be verified
        // is not a signature. (The daemon's exact bytes differ because ECDSA
        // nonces differ between libraries; what must hold is that the key that
        // signs is the key derived here, and that the daemon would accept it.)
        let publicKey = try Secp256k1.publicKey(fromPrivateKey: key.privateKey)
        XCTAssertTrue(try Secp256k1.verify(derSignature: signature, digest: digest, publicKey: publicKey))

        // And the daemon's own public key for that path must verify a signature
        // from the same scalar — the point being the keys agree, not the nonces.
        let expectedPublicKey = try Hex.decode(try XCTUnwrap(vectors[0].paths["m/0/0"]).publicKeyHex)
        XCTAssertEqual(Hex.encode(publicKey), Hex.encode(expectedPublicKey))
        XCTAssertTrue(try Secp256k1.verify(derSignature: signature, digest: digest, publicKey: expectedPublicKey))
    }

    func testPhraseValidationRejectsTypoAndAcceptsVectors() throws {
        for vector in try loadVectors() {
            XCTAssertNoThrow(try BIP39.validate(vector.phrase), "the vector phrases are valid")
        }
        // A mistyped word must fail loudly rather than derive a different wallet
        // and let the user discover it from an empty balance.
        let typo = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon"
        XCTAssertThrowsError(try BIP39.validate(typo)) { error in
            XCTAssertEqual(error as? BIP39.Error, .badChecksum, "a valid-worded but wrong phrase fails the checksum")
        }
        XCTAssertThrowsError(try BIP39.validate("notaword abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about")) { error in
            XCTAssertEqual(error as? BIP39.Error, .unknownWord("notaword"))
        }
        XCTAssertThrowsError(try BIP39.validate("abandon abandon")) { error in
            XCTAssertEqual(error as? BIP39.Error, .wrongWordCount(2))
        }
    }

    func testTheWordlistIsTheRealBIP39EnglishList() throws {
        let list = try BIP39.wordlist()
        XCTAssertEqual(list.count, 2048)
        XCTAssertEqual(list["abandon"], 0, "the list's order carries the index")
        XCTAssertEqual(list["zoo"], 2047)
        XCTAssertEqual(list["legal"], 1019, "a mid-list word, so the file cannot be truncated")
        // BIP39's English list is sorted; a shuffled or partially-copied file
        // would still have 2048 entries and the right endpoints.
        let words = list.sorted { $0.value < $1.value }.map(\.key)
        XCTAssertEqual(words, words.sorted(), "the word list is in the specified order")
    }

    /// RIPEMD160 against the algorithm's published vectors, because CryptoKit has
    /// no RIPEMD160 and this one is mine.
    func testRIPEMD160MatchesTheSpecification() {
        func hash(_ text: String) -> String { Hex.encode(RIPEMD160.hash(Array(text.utf8))) }
        XCTAssertEqual(hash(""), "9c1185a5c5e9fc54612808977ee8f548b2258d31")
        XCTAssertEqual(hash("abc"), "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc")
        XCTAssertEqual(hash("message digest"), "5d0689ef49d2fae572b881b123a85ffa21595f36")
        XCTAssertEqual(hash("abcdefghijklmnopqrstuvwxyz"), "f71c27109c692c1b56bbdceb5b9d2865b3708dbc")
        XCTAssertEqual(hash("12345678901234567890123456789012345678901234567890123456789012345678901234567890"),
                       "9b752e45573d4b39f4dbd3323cab82bf63326bfb")
    }

    func testBase58CheckRoundTripsAndRejectsDamage() throws {
        let address = "1LqBGSKuX5yYUonjxT5qGfpUsXKYYWeabA"
        let payload = try Base58.checkDecode(address)
        XCTAssertEqual(payload.count, 21)
        XCTAssertEqual(payload[0], 0x00, "mainnet P2PKH")
        XCTAssertEqual(Base58.checkEncode(payload), address)

        // A single altered character must fail the checksum, not decode to a
        // different address.
        let damaged = String(address.dropLast()) + "B"
        XCTAssertThrowsError(try Base58.checkDecode(damaged))
        XCTAssertThrowsError(try Address.scriptHash(from: "1LqBGSKuX5yYUonjxT5qGfpUsXKYYWeab0"))
    }

    func testLockingScriptShape() throws {
        let script = try Address.lockingScript(for: "1LqBGSKuX5yYUonjxT5qGfpUsXKYYWeabA")
        XCTAssertEqual(script.count, 25, "P2PKH is always 25 bytes")
        XCTAssertEqual(Array(script.prefix(3)), [0x76, 0xa9, 0x14])
        XCTAssertEqual(Array(script.suffix(2)), [0x88, 0xac])
    }

    /// The scalar arithmetic that BIP32 needs, checked at the boundaries where a
    /// carry or a reduction bug would show up.
    func testScalarAdditionReducesExactlyOnce() throws {
        // 0 + 0 = 0
        XCTAssertEqual(try ScalarArithmetic.addModN([UInt8](repeating: 0, count: 32), [UInt8](repeating: 0, count: 32)),
                       [UInt8](repeating: 0, count: 32))
        // 1 + 1 = 2
        var one = [UInt8](repeating: 0, count: 32); one[31] = 1
        var two = [UInt8](repeating: 0, count: 32); two[31] = 2
        XCTAssertEqual(try ScalarArithmetic.addModN(one, one), two)
        // (n - 1) + 1 = 0 — the reduction case, exactly once.
        var nMinus1 = ScalarArithmetic.bytes(ScalarArithmetic.order)
        nMinus1[31] -= 1
        XCTAssertEqual(try ScalarArithmetic.addModN(nMinus1, one), [UInt8](repeating: 0, count: 32))
        // (n - 1) + 2 = 1
        XCTAssertEqual(try ScalarArithmetic.addModN(nMinus1, two), one)
    }
}
